# version format
version: 0.1.{build}-{branch}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}
image: Ubuntu
max_jobs: 1

# branches to build
branches:
  only:
    - develop
    - master
shallow_clone: true
clone_depth: 1

init:
  - nvm install 13.9.0
  - nvm use 13.9.0
install:
  - npm install
build_script:
  - npm run deploy-s3

# on successful build
on_success:
  - cmd: echo "BUILD LOG => Success"

# on build failure
on_failure:
  - cmd: echo "BUILD LOG => Failed"

# after build failure or success
on_finish:
  - cmd: echo "BUILD LOG => Finished"

# override settings for `master` branch
for:
-
  branches:
    only:
      - master
  environment:
    BUILD_ENVIRONMENT: 'stage'
  build_script:
    - npm run deploy-s3-prod
